import { StyleSheet } from "react-native";
import { COLORS } from "../constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  scrollContent: {
    flexGrow: 1,
    padding: 25,
    justifyContent: "space-between",
  },
  mainContent: {
    flex: 1,
    justifyContent: "center",
  },
  topBar: {
    position: "absolute",
    top: 0,
    left: 0,
    zIndex: 10,
  },
  backButton: {
    width: 45,
    height: 45,
    borderRadius: 12,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  headerArea: { alignItems: "center", marginBottom: 30, marginTop: 40 },
  logoCircle: {
    width: 80,
    height: 80,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(56, 189, 248, 0.1)",
    borderRadius: 40,
  },
  wifiIcon: { position: "absolute", top: 0 },
  mainTitle: {
    color: COLORS.textPrimary,
    fontSize: 22,
    fontWeight: "bold",
    marginTop: 15,
    textAlign: "center",
  },
  subTitle: {
    color: COLORS.textSecondary,
    fontSize: 13,
    marginTop: 5,
    textAlign: "center",
  },
  formCard: {
    width: "100%",
    backgroundColor: COLORS.card,
    padding: 24,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
  },
  loginText: {
    color: COLORS.textPrimary,
    fontSize: 26,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 25,
  },
  inputLabel: { color: COLORS.textSecondary, fontSize: 14, marginBottom: 8 },
  forgotPassword: {
    alignSelf: "flex-end",
    marginTop: 12,
    marginBottom: 12,
  },
  forgotText: {
    color: COLORS.primary,
    fontSize: 14,
    fontWeight: "500",
  },
  inputWrapper: {
    flexDirection: "row",
    backgroundColor: COLORS.background,
    borderRadius: 12,
    alignItems: "center",
    paddingHorizontal: 15,
    height: 55,
  },
  inputField: { flex: 1, color: "white", marginLeft: 10 },
  loginButton: {
    backgroundColor: COLORS.primary,
    height: 55,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 20,
  },
  buttonInner: { flexDirection: "row", alignItems: "center" },
  loginButtonText: { color: "white", fontSize: 16, fontWeight: "bold" },
  footerLinks: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 25,
  },
  noAccountText: { color: COLORS.textSecondary },
  registerLink: { color: COLORS.primary, fontWeight: "bold" },
  bottomDecor: { paddingVertical: 20, alignItems: "center" },
  copyrightText: {
    color: COLORS.textDisabled,
    fontSize: 11,
    textAlign: "center",
  },
});
