import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0F172A" },
  scrollContent: { padding: 20, paddingBottom: 60 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 30,
    marginTop: 10,
  },
  headerText: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
    marginLeft: 20,
  },
  roleSelector: {
    flexDirection: "row",
    borderRadius: 12,
    padding: 5,
    backgroundColor: "#1E293B",
    marginBottom: 30,
  },
  roleButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    borderRadius: 10,
  },
  activeButton: { backgroundColor: "#0369A1" },
  roleButtonText: { color: "white", fontWeight: "600", fontSize: 14 },
  inputLabel: {
    color: "#94A3B8",
    fontSize: 14,
    marginBottom: 8,
    marginTop: 15,
  },
  inputWrapper: {
    flexDirection: "row",
    backgroundColor: "#1E293B",
    borderRadius: 12,
    alignItems: "center",
    paddingHorizontal: 15,
    height: 55,
  },
  inputField: { flex: 1, color: "white", marginLeft: 10 },
  submitButton: {
    backgroundColor: "#F97316",
    height: 55,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 40,
    elevation: 5,
  },
  submitButtonText: { color: "white", fontSize: 16, fontWeight: "bold" },
  formContainer: { marginBottom: 10 },
  uploadBox: {
    backgroundColor: "#1E293B",
    height: 100,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#0369A1",
    borderStyle: "dashed",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 5,
  },
  uploadText: { color: "#64748B", fontSize: 12, marginTop: 8 },
});
